[package]
name = "unique_assets"
version = "0.1.0"
authors = ["Jay Butera <buterajay@protonmail.com>"]
edition = "2018"

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = "be8bb186d87b9d2b47a2907c9b51ae1e252362c3"
version = '2.0.0-rc6'

[dependencies.sp-std]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
rev = "be8bb186d87b9d2b47a2907c9b51ae1e252362c3"
version = '2.0.0-rc6'

[features]
default = [ "std" ]
std = [
    "frame-support/std",
    "sp-std/std",
]
